name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options:
          - order_hotel_test
          - correct_order_test
          - cancel_order_test
          - filter_order_test
          - cancel_AA_test
          - order_two_guests_test

jobs:
  tests:
    runs-on: macos-latest
    permissions:
      contents: read  # Прочтение репозитория
      id-token: write  # Разрешение для получения и использования ID токенов
      actions: read     # Разрешение для чтения артефактов GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Кэширование зависимостей Python
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Chrome
        run: brew install --cask google-chrome

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Запуск тестов в зависимости от выбранной цели
      - name: Run tests based on deployment target
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "order_hotel_test" ]; then
            pytest tests/test_order_hotel.py --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "correct_order_test" ]; then
            pytest tests/test_correct_order_hotel.py --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "cancel_order_test" ]; then
            pytest tests/test_cancel_order_hotel.py --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "filter_order_test" ]; then
            pytest tests/test_filter_hotel.py --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "cancel_AA_test" ]; then
            pytest tests/test_order_hotel_AA.py --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "order_two_guests_test" ]; then
            pytest tests/test_order_hotel_two_guests.py --alluredir=allure-results
          fi

      # Проверка содержимого allure-results после выполнения тестов
      - name: List allure-results content
        run: |
          echo "Listing contents of allure-results directory"
          ls -R allure-results || echo "allure-results not found"

      # Хранение результатов тестов (Allure results)
      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ github.event.inputs.deployment_target }}
          path: allure-results
          retention-days: 7

  generate-report:
    runs-on: macos-latest
    needs: tests
    name: Generate Allure Report
    permissions:
      actions: read  # Разрешение для чтения артефактов
      contents: read  # Прочтение репозитория
      id-token: write  # Разрешение для получения и использования ID токенов
    steps:
      - name: Install Allure Commandline
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip
          unzip allure.zip
          sudo mv allure-2.18.1 /usr/local/allure
          sudo ln -s /usr/local/allure/bin/allure /usr/local/bin/allure

      - name: Check Allure version
        run: allure --version

      # Загрузка артефактов с результатами тестов
      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-${{ github.event.inputs.deployment_target }}
          path: allure-results
          merge-multiple: true

      # Проверка содержимого папки allure-results
      - name: List allure-results content
        run: |
          echo "Listing contents of allure-results directory"
          ls -R allure-results || echo "allure-results directory not found"

      # Убедитесь, что директория _site существует и очищена
      - name: Ensure _site directory exists
        run: |
          echo "Checking if _site exists..."
          if [ -d "_site" ]; then
            echo "_site exists, cleaning up..."
            rm -rf _site
          else
            echo "_site does not exist, creating it..."
            mkdir -p _site
          fi

      # Генерация отчета Allure
      - name: Generate Allure Report
        run: |
          echo "Listing contents of allure-results directory"
          ls -R allure-results || echo "allure-results directory not found"
          allure generate -c allure-results -o _site || (echo "Allure report generation failed" && exit 1)

      # Проверка содержимого директории _site после генерации отчета
      - name: List files in _site after report generation
        run: |
          echo "Listing files in _site"
          ls -R _site || echo "_site directory not found"

      # Хранение сгенерированного отчета
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site-${{ github.run_id }}-${{ github.sha }}
          path: _site
          retention-days: 7
          overwrite: false  # Уникальное имя, предотвращает перезапись

  publish-report:
    runs-on: macos-latest
    needs: generate-report
    permissions:
      contents: write  # Для деплоя в GitHub Pages
      id-token: write  # Разрешение для работы с id-token
      actions: read     # Разрешение для чтения артефактов GitHub Actions
      pages: write      # Разрешение для записи в GitHub Pages (важное изменение!)
    name: Publish Allure Report to GitHub Pages
    steps:
      - name: Download generated report
        uses: actions/download-artifact@v4
        with:
          name: _site-${{ github.run_id }}-${{ github.sha }}
          path: _site
          merge-multiple: true

      # Шаг для удаления символических ссылок в подкаталогах _site
      - name: Remove symbolic links recursively in _site
        run: |
          echo "Removing symbolic links recursively in _site directory..."
          find _site -type l -exec rm -v {} \; || echo "No symbolic links found to remove"

      # Проверка содержимого _site после удаления ссылок
      - name: List contents of _site after removing symlinks
        run: |
          echo "Listing contents of _site after removing symlinks"
          ls -alR _site || echo "_site directory not found"

      # Шаг для проверки жестких ссылок
      - name: Verify no hard links in _site before deploy
        run: |
          echo "Checking for hard links in _site directory before deploy..."
          hard_links=$(find _site -type f -links +1)
          if [ -n "$hard_links" ]; then
            echo "Hard links found before deploy, listing them:"
            echo "$hard_links"
            exit 1
          else
            echo "No hard links found in _site"
          fi

      # Проверка прав доступа в _site
      - name: Check permissions of files in _site
        run: |
          echo "Checking permissions of files in _site"
          find _site -exec ls -l {} \; || echo "Error checking permissions"

      # Шаг для удаления скрытых файлов в _site
      - name: Remove hidden files in _site
        run: |
          echo "Removing hidden files in _site directory..."
          find _site -name ".*" -exec rm -rf {} \; || echo "No hidden files found to remove"

      # Проверка отсутствия символических ссылок перед деплоем
      - name: Verify no symlinks in _site before deploy
        run: |
          echo "Checking for symbolic links in _site directory before deploy..."
          symlinks=$(find _site -type l)
          if [ -n "$symlinks" ]; then
            echo "Symbolic links found before deploy, listing them:"
            echo "$symlinks"
            exit 1
          else
            echo "No symbolic links found in _site"
          fi

      # Проверка размера директории _site
      - name: Check the size of _site directory
        run: |
          echo "Checking the size of _site directory..."
          du -sh _site || echo "_site directory not found"

      # Загрузка артефактов для деплоя
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site

      # Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: _site-${{ github.run_id }}-${{ github.sha }}
          preview: false
  